name: dev
on:
  push:
     branches: none
     
jobs:
  Offer_letter:   
    runs-on: windows-latest
    steps:
      - name: offer letter
        run: echo "I accepted offer letter,started onboarding process"
