name: main
on:
  pull_request:
     branches: [main]
     
jobs:
   details:
     runs-on: windows-latest
     steps: 
       - name: bankdetails
         run: echo "successfull opened my new acoount"
         
       - name: educationdetails
         run: echo "i have completed my engineering"
         
       - name: offerletter
         run: echo "i have got an offerletter" 
   Employee:
      runs-on: windows-latest
      steps:
        - name: employeedetails
          run: echo "i have got job"
          
  
