name: myfirsttest
on:
  push:
     branches: [dev]
     
jobs:
  GithubActions:   
    runs-on: windows-latest
    steps:
      - name: offer letter
        run: echo "I accepted offer letter,started onboarding process"
