name: workflow
on:
  push:
     branches: [dev]

  workflow_dispatch:

jobs:
  build:
    name: Hello world
    runs-on: windows-latest
    steps:
      - name: Check out repo        
        uses: actions/checkout@v2
      - run: |
          ./build.ps1
        shell: pwsh
